### PR TITLE
triples-workbench

### PR DESCRIPTION
**Pull request by rlzijdeman**
Hi, here's another use case from WP4 to store, browse, query triples and visualize query results

### CODE REVIEW

**Comment by proycon** [comment]
Great! merged

**Comment by proycon** [comment]
I think this may be more a 'generic' use case than a one tied to a very specific research, right?

**Comment by rlzijdeman** [comment]
> I think this may be more a 'generic' use case than a one tied to a very specific research, right?

Hi @proycon , that's correct. but 'generic' makes it also more fundamental -> if we have no place to store, browse, exchange and query Linked Data, no research question can be tackled FAIRly. For an overview of some light weight research questions that we have been asking see: [https://stories.datalegend.net](https://stories.datalagend.net).

**Comment by proycon** [comment]
@rlzijdeman Yes, I understand, I merely meant to suggest that perhaps the type for this use case should be set to 'generic' rather than to 'specific', as it is now. Generic use cases are most welcome too of course.

**Pull request merged**
